name: Bump version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Which SemVer'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
  workflow_call:
    inputs:
      semver:
        description: The image_name to build for.
        required: true
        type: string
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm version ${{ inputs.semver }} --no-git-tag-version
      - name: generate new version and save to env variable
        id: get_version
        run: |
          echo "NEW_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_OUTPUT

      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          base: main
          branch: release
          commit-message: 'bump: v${{ steps.get_version.outputs.NEW_VERSION }}'
          body: ${{ steps.get_release_note.outputs.result  }}
          title: 'chore: bump v${{ steps.get_version.outputs.NEW_VERSION }}'
          draft: true
          milestone: 'v${{ steps.get_version.outputs.NEW_VERSION }}'
